import assert from'node:assert/strict';import fs from'node:fs/promises';import path from'node:path';import os from'node:os';import{fileURLToPath,pathToFileURL}from'node:url';import{build}from'esbuild';import * as THREE from'three';import{loadBodyPreview}from'./body-shape-visual-loader.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),tmp=path.join(os.tmpdir(),`hair-test-${process.pid}.mjs`);await build({stdin:{contents:"export * as hair from './src/render/previewHair.ts';export * as shape from './src/render/bodyShape.ts';export * as pose from './src/render/bodyPose.ts';export * as appearance from './src/render/bodyAppearance.ts';",resolveDir:root,loader:'ts'},outfile:tmp,bundle:true,platform:'node',format:'esm',logLevel:'silent'});const m=await import(pathToFileURL(tmp));await fs.unlink(tmp);const times=[];let count=0;
for(const sex of['male','female']){const{geometry:source}=await loadBodyPreview(root,sex),g=source.toNonIndexed();source.dispose();const d=m.shape.prepareDeformable(g),bounds=m.shape.shapeBounds([d]),base=d.base;const none=m.hair.createPreviewHair(g,base,bounds,{hairStyle:'none',hairTone:'black'});assert.equal(none.children.length,0);assert.ok(m.hair.createHairCoverage(base,bounds,{hairStyle:'none'}).every(v=>v===0));
for(const style of['buzz','short']){
 const coverage=m.hair.createHairCoverage(base,bounds,{hairStyle:style});assert.ok(coverage.some(v=>v===1));const field=m.hair.createHairScalpField(base,bounds);assert.equal(coverage.length,g.attributes.position.count);let face=0;for(let i=0;i<coverage.length;i++){const h=(base[i*3+1]-bounds.minY)/(bounds.maxY-bounds.minY);if(h<.89){assert.equal(coverage[i],0);face++;}assert.ok(Number.isFinite(field[i]));}assert.ok(face>100);
 const appearance={hairStyle:style,hairTone:'dark_brown'},initialPosition=g.attributes.position.array.slice(),initialNormal=g.attributes.normal.array.slice();let original;
 for(let repeat=0;repeat<6;repeat++){const start=performance.now(),group=m.hair.createPreviewHair(g,base,bounds,appearance);times.push(performance.now()-start);const geo=group.children[0].geometry;assert.ok(geo.attributes.position.array.every(Number.isFinite));assert.ok(geo.attributes.normal.array.every(Number.isFinite));assert.ok(group.userData.triangleCount<8000);assert.ok(group.userData.lockCount>800);assert.deepEqual(g.attributes.position.array,initialPosition);assert.deepEqual(g.attributes.normal.array,initialNormal);if(!original)original=geo.attributes.position.array.slice();else assert.deepEqual(geo.attributes.position.array,original);m.hair.disposePreviewHair(group);count++;}
 const rotation=new THREE.Matrix4().makeRotationFromEuler(new THREE.Euler(.2,.6,-.22));rotation.setPosition(.13,-.07,.04);g.applyMatrix4(rotation);const transformed=m.hair.createPreviewHair(g,base,bounds,appearance).children[0].geometry.attributes.position.array;assert.equal(transformed.length,original.length);const v=new THREE.Vector3();let maximum=0;for(let i=0;i<original.length;i+=3){v.fromArray(original,i).applyMatrix4(rotation);maximum=Math.max(maximum,Math.abs(v.x-transformed[i]),Math.abs(v.y-transformed[i+1]),Math.abs(v.z-transformed[i+2]));}assert.ok(maximum<2e-5,`${sex} ${style} rigid attachment error ${maximum}`);g.attributes.position.array.set(initialPosition);g.attributes.normal.array.set(initialNormal);
}
for(const tone of m.appearance.HAIR_TONES){m.shape.applyBodyShape([d],bounds,m.shape.normalizeShape({head:tone.id==='blond'?1:-1,height:tone.id==='blond'?1:-1}));m.pose.applyBodyPose([d],bounds,m.pose.normalizePose({headTurn:35,headTilt:-15}));const group=m.hair.createPreviewHair(g,base,bounds,{hairStyle:'short',hairTone:tone.id});assert.ok(group.children[0].geometry.attributes.position.array.every(Number.isFinite));assert.ok(group.children[0].geometry.attributes.color.array.every(v=>Number.isFinite(v)&&v>=0&&v<=1));m.hair.disposePreviewHair(group);count++;}
g.dispose();console.log(`${sex}: none/buzz/short, six tones, head extremes/rotation, deterministic scalp, rigid attachment and source preservation passed.`);}
times.sort((a,b)=>a-b);console.log(`${count} hair builds passed; triangles <8000, median ${times[Math.floor(times.length*.5)].toFixed(1)}ms, p95 ${times[Math.floor(times.length*.95)].toFixed(1)}ms.`);
