import fs from 'node:fs/promises';import path from 'node:path';import os from 'node:os';import{fileURLToPath,pathToFileURL}from'node:url';import{build}from'esbuild';import{spawnSync}from'node:child_process';import * as THREE from'three';import{loadBodyPreview}from'./body-shape-visual-loader.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),out=path.join(root,'reports/hair/final');await fs.mkdir(out,{recursive:true});const temp=path.join(os.tmpdir(),`hair-${process.pid}.mjs`);await build({stdin:{contents:"export * as hair from './src/render/previewHair.ts';export * as shape from './src/render/bodyShape.ts';export * as pose from './src/render/bodyPose.ts';export * as appearance from './src/render/bodyAppearance.ts';",resolveDir:root,loader:'ts'},outfile:temp,bundle:true,platform:'node',format:'esm',logLevel:'silent'});const m=await import(pathToFileURL(temp));await fs.unlink(temp);const report={cases:[]};
async function write(name,data){await fs.writeFile(path.join(out,name),Buffer.from(data.buffer,data.byteOffset,data.byteLength));}
for(const sex of['male','female']){const{geometry,matrix}=await loadBodyPreview(root,sex),prepared=m.shape.prepareDeformable(geometry),bounds=m.shape.shapeBounds([prepared]);
const cases=[...['none','buzz','short'].map(style=>({id:style,style,tone:'dark_brown'})),{id:'short-posed-small',style:'short',tone:'brown',shape:{head:-1,height:-1},pose:{headTurn:35,headTilt:15}},{id:'short-posed-large',style:'short',tone:'blond',shape:{head:1,height:1},pose:{headTurn:-35,headTilt:-15}},...(sex==='male'?m.appearance.HAIR_TONES.map(t=>({id:`tone-${t.id}`,style:'short',tone:t.id})):[])];
for(const spec of cases){m.shape.applyBodyShape([prepared],bounds,m.shape.normalizeShape(spec.shape));m.pose.applyBodyPose([prepared],bounds,m.pose.normalizePose(spec.pose));const group=m.hair.createPreviewHair(geometry,prepared.base,bounds,{hairStyle:spec.style,hairTone:spec.tone});const body=geometry.toNonIndexed(),bodyPos=body.attributes.position.array,base=prepared.base,sourceIndex=geometry.index;
const p=[],n=[],c=[];const normalMatrix=new THREE.Matrix3().getNormalMatrix(matrix),v=new THREE.Vector3(),headBox=new THREE.Box3();
// Keep complete head triangles; the inspection cut is below the hairline.
for(let f=0;f<bodyPos.length/3;f+=3){if([0,1,2].some(k=>(base[(sourceIndex?sourceIndex.getX(f+k):f+k)*3+1]-bounds.minY)/(bounds.maxY-bounds.minY)<.87))continue;for(let k=0;k<3;k++){v.fromBufferAttribute(body.attributes.position,f+k).applyMatrix4(matrix);p.push(v.x,v.y,v.z);headBox.expandByPoint(v);v.fromBufferAttribute(body.attributes.normal,f+k).applyMatrix3(normalMatrix).normalize();n.push(v.x,v.y,v.z);c.push(.45,.30,.215);}}
for(const mesh of group.children){const g=mesh.geometry;for(let i=0;i<g.attributes.position.count;i++){v.fromBufferAttribute(g.attributes.position,i).applyMatrix4(matrix);p.push(v.x,v.y,v.z);headBox.expandByPoint(v);v.fromBufferAttribute(g.attributes.normal,i).applyMatrix3(normalMatrix).normalize();n.push(v.x,v.y,v.z);c.push(g.attributes.color.getX(i),g.attributes.color.getY(i),g.attributes.color.getZ(i));}}
const id=`${sex}-${spec.id}`;for(const[name,data]of[['positions',p],['normals',n],['colors',c]])await write(`${id}-${name}.f32`,Float32Array.from(data));report.cases.push({...spec,id,sex,center:headBox.getCenter(new THREE.Vector3()).toArray(),dimensions:headBox.getSize(new THREE.Vector3()).toArray(),triangles:group.userData.triangleCount??0,locks:group.userData.lockCount??0});m.hair.disposePreviewHair(group);body.dispose();}
 geometry.dispose();}
await fs.writeFile(path.join(out,'manifest.json'),JSON.stringify(report,null,2));console.log(report.cases.map(c=>`${c.id}: ${c.triangles} hair triangles`).join('\n'));const proc=spawnSync(process.env.HAIR_PYTHON||'python3',[path.join(root,'tools/hair-visual.py'),out],{stdio:'inherit'});process.exitCode=proc.status??1;
